//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_administrativa {
    
    
    public partial class PanelGeneral {
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new Gestion_administrativa.Home Master {
            get {
                return ((Gestion_administrativa.Home)(base.Master));
            }
        }
    }
}
